version: '3'

services:
  nginx:
    image: 'nginx:1.19.3-alpine'
    ports:
      - '50080:80'
    networks:
      - frontend
    volumes:
      - './default.nginx:/etc/nginx/conf.d/default.conf'
      - './html:/var/www'
    restart: always
    depends_on:
      - api

  api:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - frontend
      - default
    ports:
      - '58080:8080'
    restart: always

networks:
  frontend:
    driver: bridge
